name: Release VSIX

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases and upload assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install vsce
        run: npm install -g vsce

      - name: Build VSIX package
        run: vsce package
      - name: Get Short Commit SHA
        run: echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          # Find the generated vsix file. The name is usually <extension-name>-<version>.vsix
          artifacts: "*.vsix"
          # GITHUB_TOKEN is provided automatically
          token: ${{ secrets.GITHUB_TOKEN }}
          # Use the short commit hash as the release tag.
          tag: ${{ env.SHORT_SHA }}
          # Use the notes fetched from the changelog script as the release body
          body: ${{ steps.changelog.outputs.notes }}
          # Make this release the 'Latest' release
          makeLatest: true
